name: Sync to CNB
on: 
 - push
 - delete

jobs:
  sync-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: clone test
        run: |
          dig cnb.cool
          GIT_CURL_VERBOSE=1 git clone https://cnb.cool/vincent/vincent927.github.io liuhuan-test
      - name: Sync to CNB Repository
        run: |
          echo ${{ secrets.CNB_TOKEN }}
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLUGIN_TARGET_URL="https://cnb.cool/vincent/vincent927.github.io" \
            -e PLUGIN_AUTH_TYPE="https" \
            -e PLUGIN_USERNAME="cnb" \
            -e PLUGIN_PASSWORD="cauaVrIr7myw41b47dURDwz6o4C" \
            -e PLUGIN_PUSH_TAGS="true" \
            -e PLUGIN_FORCE="true" \
            tencentcom/git-sync
